ARG PHP_VERSION

FROM web-img-farwish:${PHP_VERSION}

USER root

# Integrate  NODE environment
RUN apt-get update && apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update && apt-get install -y nodejs \
    && npm install -g webpack && npm install -g vue-cli

## Run `sudo apt-get install -y nodejs` to install Node.js 10.x and npm
## You may also need development tools to build native addons:
#     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
#     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
#     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#     sudo apt-get update && sudo apt-get install yarn

USER www-data

ARG WEB_PATH

WORKDIR ${WEB_PATH}
